default_platform(:ios)

platform :ios do
  desc "Build and upload to TestFlight"
  lane :beta do
    setup_ci if ENV['CI']
    build_app(
      project: Dir.glob("*.xcodeproj").first,
      scheme: ENV.fetch("CRAFTSMAN_SCHEME", Dir.glob("*.xcodeproj").first&.gsub('.xcodeproj','')),
      export_method: "app-store"
    )
    upload_to_testflight(skip_waiting_for_build_processing: true) if ENV["APP_STORE_CONNECT_API_KEY"]
  end
end
